target 'MercadoBitcoin' do
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.15'
  pod 'SwiftGen'
end

target "MercadoBitcoinTests" do
  use_frameworks!

  pod 'iOSSnapshotTestCase'
end
